apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    k8slens-edit-resource-version: v1alpha1
  name: pongsit-infra
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'